name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com/"
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: Lint & Test
        run: yarn lint && yarn test
      
      - name: Fix Remote URL
        run: git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release